### ISSUE TITLE
Create knowledge base - Guides

### ISSUE THREAD

**Issue by jcastle** [GSA/cto-website#3]
8/16 - use this for reference.  Moving to UK model, framework, and stories in the Kanban by topic area.

------------------------------
Consider area for docs/playbooks for content

- [x] consider layout ideas - maybe take the USDS playbook, see what 18F has for manuals
- [ ] start with Agile docs/content - "documents, language, roles & resp; agile roles, contract language, how do you know you are doing Agile well, structure that would work with the content"
- [ ] Expand knowledge repository using 18f pages template for Team (admin, onboarding, hiring) and Knowledge (tools, agile, best practices) spaces.
Consider extensions off the url CTO/team.

**Comment by jfredrickson5** [comment]
Will create the KB framework during Sprint 1; load content during future sprints.

**Comment by jcastle** [comment]
Maybe leave link off home page until content is agreed to by Navin, only we can find it by URL

**Comment by saracope** [comment]
Expand knowledge repository using 18f pages template for Team (admin, onboarding, hiring) and Knowledge (tools, agile, best practices) spaces.
Consider extensions off the url CTO/team.
Will talk about this more with the team.

**Comment by saracope** [comment]
Adding @CinnyaSm to help with content.

**Comment by jfredrickson5** [comment]
For reference: https://pages.18f.gov/dev-environment/

**Comment by jcastle** [comment]
the knowledge base can be done with guides, I will begin setting up template guides as I think we need this off of the vision page too

**Comment by jcastle** [comment]
@jfredrickson5, we might want to create sub menu items to categorize.  I was thinking of a guide for onboard which has to do with hiring.  The current guides focus on high-level strategic ideas like being Agile.  Then I have another guide for starting an Agile project.

We also want to consider a place to store documents, even if it's a running page separated by category.

**Comment by jcastle** [comment]
@jfredrickson5 need a way to do sub-guides.  Noticed that 18F takes you to a new page with new structure in the left on some of their guides, maybe all of them.  We should look at this approach.

Also, guides breaks when you click on a link "onboarding" and then another "link."  It seems to lose part of the base URL.

**Comment by jcastle** [comment]
Let's establish a framework.  UK Service Guide looks more robust as a design idea.  https://www.gov.uk/service-manual
